remote_theme:       mmistakes/so-simple-theme
skin:               "/assets/css/skins/default.css"
locale:             en-US
title:              "Dev With Nguyen Blog"
description:        "Góc riêng của Phùng Khôi Nguyên - Andrew"
baseurl:            # the subpath of your site, e.g. "/blog"
url:                "https://pknguyen2704.github.io"
logo:               "/images/andrewphung_logo.png"
date_format:        "%B %-d, %Y"
read_time:          true
words_per_minute:   200
mathjax:
  enable:           true
  combo:            # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:             # "none", "ams" (default), "all"
google_fonts:
  - name:           "Source Sans Pro"
    weights:        "400,400i,700,700i"
  - name:           "Lora"
    weights:        "400,400i,700,700i"
google_analytics:   # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname:        # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username:         # site's Twitter username, e.g. "mmistakes"

liquid:
  error_mode:       strict

permalink:          /:categories/:title/
markdown:           kramdown
feed:
  path:             atom.xml

paginate: 10
paginate_path:      /page:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

author: andrewphung

footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: Instagram
